### ISSUE TITLE
READY FOR TESTING SLACKBUILDS

### ISSUE THREAD

**Issue by rizitis** [0xBOBF/gnome-42-slackbuilds#1]
[gfbgraph.SlackBuild.zip](https://github.com/0xBOBF/gnome-42-slackbuilds/files/8552138/gfbgraph.SlackBuild.zip)

**Comment by rizitis** [comment]
[gnome-backgrounds.SlackBuild.zip](https://github.com/0xBOBF/gnome-42-slackbuilds/files/8552253/gnome-backgrounds.SlackBuild.zip)

**Comment by rizitis** [comment]
[gnome-calculator.SlackBuild.zip](https://github.com/0xBOBF/gnome-42-slackbuilds/files/8552420/gnome-calculator.SlackBuild.zip)

**Comment by rizitis** [comment]
[amtk.SlackBuild.zip](https://github.com/0xBOBF/gnome-42-slackbuilds/files/8552471/amtk.SlackBuild.zip)

**Comment by rizitis** [comment]
[libgnomekbd.SlackBuild.zip](https://github.com/0xBOBF/gnome-42-slackbuilds/files/8552494/libgnomekbd.SlackBuild.zip)

**Comment by rizitis** [comment]
[gnome-tweaks.SlackBuilds.zip](https://github.com/0xBOBF/gnome-42-slackbuilds/files/8552611/gnome-tweaks.SlackBuilds.zip)

**Comment by rizitis** [comment]
[geocode-glib.SlackBuild.zip](https://github.com/0xBOBF/gnome-42-slackbuilds/files/8553009/geocode-glib.SlackBuild.zip)

**Comment by rizitis** [comment]
[gnome-applets.SlackBuild.zip](https://github.com/0xBOBF/gnome-42-slackbuilds/files/8553037/gnome-applets.SlackBuild.zip)

**Comment by rizitis** [comment]
[gnome-bluetooth.SlackBuild.zip](https://github.com/0xBOBF/gnome-42-slackbuilds/files/8553121/gnome-bluetooth.SlackBuild.zip)

**Comment by rizitis** [comment]
[gnome-builder.SlackBuild.zip](https://github.com/0xBOBF/gnome-42-slackbuilds/files/8553133/gnome-builder.SlackBuild.zip)

**Comment by rizitis** [comment]
[gnome-calendar.SlackBuild.zip](https://github.com/0xBOBF/gnome-42-slackbuilds/files/8553146/gnome-calendar.SlackBuild.zip)

**Comment by rizitis** [comment]
[gnome-shell.SlackBuild.zip](https://github.com/0xBOBF/gnome-42-slackbuilds/files/8553219/gnome-shell.SlackBuild.zip)

**Comment by rizitis** [comment]
[sushi.SlackBuild.zip](https://github.com/0xBOBF/gnome-42-slackbuilds/files/8553343/sushi.SlackBuild.zip)

**Comment by rizitis** [comment]
[sysprof.SlackBuild.zip](https://github.com/0xBOBF/gnome-42-slackbuilds/files/8553353/sysprof.SlackBuild.zip)

**Comment by rizitis** [comment]
[template-glib.SlackBuild.zip](https://github.com/0xBOBF/gnome-42-slackbuilds/files/8553361/template-glib.SlackBuild.zip)

**Comment by rizitis** [comment]
[geocode-glib.SlackBuild.zip](https://github.com/0xBOBF/gnome-42-slackbuilds/files/8553009/geocode-glib.SlackBuild.zip)

**Comment by 0xBOBF** [comment]
I'll leave this up for now, but we can close this once these slackbuilds are in their appropriate directory.

**Comment by rizitis** [comment]
closed
